### Clean RepRisk Data

* August 23 2026

In [2]:
import pandas as pd
import numpy as np
import re

import identifier

In [12]:
reader = pd.read_stata(r"D:\Dropbox\Dropbox\Dropbox\4_SASB\Shared Data\RepRisk\Company_Identifiers\hpsvj5a53yuf4hjg.dta",
    iterator=True,
    chunksize=100000
)

us_chunks = []

for chunk in reader:
    us = chunk[
        chunk['headquarters_country_isocode'].str.strip().eq('US')
    ]
    
    if len(us) > 0:
        us_chunks.append(us)

identifier = pd.concat(us_chunks, ignore_index=True)
print(len(identifier))

C:\Users\huipi\AppData\Local\Temp\ipykernel_19712\1642607876.py:8: UnicodeWarning:
One or more strings in the dta file could not be decoded using utf-8, and
so the fallback encoding of latin-1 is being used.  This can happen when a file
has been incorrectly encoded by Stata or some other software. You should verify
the string values returned are correct.
  for chunk in reader:

187316

In [13]:
identifier['no_reported_risk_exposure'].value_counts()

no_reported_risk_exposure
true     137260
false     50056
Name: count, dtype: int64

In [14]:
identifier = identifier[['reprisk_id', 'company_name', 'sectors', 'url', 'isins', 'primary_isin', 'no_reported_risk_exposure']]
identifier.head()

,reprisk_id,company_name,sectors,url,isins,primary_isin,no_reported_risk_exposure
0,1000015,Sevanta Systems Corp,Support Services (Industrial Goods and Services),http://sevanta.com/,,,true
1,1000090,Food Management Partners Inc,Travel and Leisure,http://www.foodmps.com/,,,false
2,10001,Harleysville Group Inc,Insurance,https://www.harleysvillegroup.com/,US4128241043,US4128241043,true
3,100014,Waverider Communications Inc,Technology Hardware and Equipment,,US9435703098 | US9435704088,US9435704088,true
4,100015,Wireless Data Solutions Inc,Technology Hardware and Equipment,,US78473G1085,US78473G1085,true

import Reprisk 2018

In [15]:
reader = pd.read_stata(r"D:\Dropbox\Dropbox\Dropbox\4_SASB\Shared Data\RepRisk\Metrics_2018_Reprisk.dta\jfe5szbphv9tffjl.dta",
    iterator=True,
    chunksize=100000
)

us_chunks = []

for chunk in reader:
    us = chunk[
        chunk['headquarters_country_isocode'].str.strip().eq('US')
    ]
    
    if len(us) > 0:
        us_chunks.append(us)

reprisk2018 = pd.concat(us_chunks, ignore_index=True)
print(len(reprisk2018))

18211310

In [17]:
reprisk2018.columns

Index(['reprisk_id', 'date', 'company_name', 'headquarters_country_isocode',
       'primary_isin', 'current_rri', 'trend_rri', 'peak_rri', 'peak_rri_date',
       'reprisk_rating', 'country_sector_average', 'principle1_human_rights',
       'principle2_human_rights', 'principle3_labour', 'principle4_labour',
       'principle5_labour', 'principle6_labour', 'principle7_environment',
       'principle8_environment', 'principle9_environment',
       'principle10_anti_corruption'],
      dtype='object')

In [ ]:
## drop those without a primary ISIN
reprisk2018['primary_isin'].str.strip().ne('').sum()

1891065

In [ ]:
reprisk2018 = reprisk2018[
    reprisk2018['primary_isin'].str.strip() != ''
].copy()

In [ ]:
reprisk2018 = reprisk2018[['reprisk_id', 'company_name','date', 'current_rri', 'trend_rri', 'peak_rri', 'reprisk_rating']]

In [49]:
reprisk2018.head()

,reprisk_id,company_name,date,current_rri,trend_rri,peak_rri,reprisk_rating
14,100046,Revitas Inc (formerly iMany Inc),2018-01-01,0.0,0.0,0.0,AA
16,1000563,Foghorn Therapeutics Inc,2018-01-01,0.0,0.0,0.0,AA
18,100077,Red Mountain Resources Inc,2018-01-01,0.0,0.0,0.0,AA
19,10010,PDC Energy Inc (formerly Petroleum Development...,2018-01-01,24.0,-6.0,30.0,A
20,10013,Old National Bancorp Inc,2018-01-01,0.0,0.0,0.0,AA

In [26]:
reprisk2018['principle1_human_rights'].value_counts()

principle1_human_rights
                                   18196174
POTENTIAL_VIOLATOR_OPERATIONS          8092
POTENTIAL_VIOLATOR_SUPPLY_CHAIN        5593
VIOLATOR_OPERATIONS                     835
VIOLATOR_SUPPLY_CHAIN                   616
Name: count, dtype: int64

Reprisk 2019

In [51]:
reader = pd.read_stata(
    r"D:\Dropbox\Dropbox\Dropbox\4_SASB\Shared Data\RepRisk\Metrics_2019_Reprisk.dta\estpgmvpwahjtppf.dta",
    iterator=True,
    chunksize=100000
)

us_chunks = []

for chunk in reader:
# import data in chunks and filter for US companies with a primary ISIN
    us = chunk[
        (chunk['headquarters_country_isocode'].str.strip() == 'US') &
        (chunk['primary_isin'].str.strip() != '')
    ]

    if len(us) > 0:
        us_chunks.append(us)

reprisk2019 = pd.concat(us_chunks, ignore_index=True)

print(len(reprisk2019))

1891430

In [ ]:
reprisk2019 = reprisk2019[
    reprisk2019['primary_isin'].str.strip() != ''
].copy()

reprisk2019 = reprisk2019[['reprisk_id', 'company_name','date', 'current_rri', 'trend_rri', 'peak_rri', 'reprisk_rating']]
reprisk2019.head()

Reprisk 2020

Reprisk 2021

Reprisk 2022

Reprisk 2023